### PR TITLE
Support gradle 8.0

### PR DESCRIPTION
**Pull request by wadihhannouch**
Update app gradle and AndroidManifest

### CODE REVIEW

**Comment by elmanna** [comment]
hello, كيف حالك, 

isn't changing or removing the attribute "package" which was -> ( package="com.elmanna.dev.multipart_request_null_safety" ), From the manifest tag lead to failures in building the the package?

**Comment by wadihhannouch** [comment]
Hey mate
الحمدلله  و انت؟
No mate if your android app supports gradle 8.0, which recently is required to publish an app. This should work fine, and that's what i have done to be able to release mine

**Comment by elmanna** [comment]
الحمدالله، 
تمام إذاً 👍

**Comment by elmanna** [comment]
شنو أسم تطبيقك خليني أللقي نظرة عليه، 
حلو اشوف الmultipart شغال عليه

**Pull request merged**
